// LLVM Compiler for the Puma programming language
//   as defined in the document "The Puma Programming Language Specification"
//   available at https://github.com/ThePumaProgrammingLanguage
//
// Copyright © 2024-2025 by Darryl Anthony Burchfield
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

using Microsoft.VisualStudio.TestPlatform.Utilities;
using System.Diagnostics;
using System.IO;
using System.Reflection;

namespace Puma
{
    internal class Program
    {
        // variables to store the command-line arguments.
        protected static string ClangArguments = "";
        protected static bool Verbose = false;
        protected static bool Help = false;
        protected static bool Version = false;
        protected static bool EmitC = false;
        protected static bool Output = false;
        protected static string SourceFileName = "";
        protected static string OutputFileName = "";
        // variable to store the source code.
        protected static string source = "";
        
        /// <summary>
        /// // Main method of the Puma compiler.
        /// </summary>
        /// <param name="args"></param>
        static void Main(string[] args)
        {
            // Parse the command-line arguments.
            ParseCommandArguments(args);

            var cSourceFileName = SourceFileName.Replace(".puma", ".c");

            if (Help)
            {
                // Print the help message and return.
                PrintHelp();
                return;
            }

            if (Version)
            {
                var versionNumber = Assembly.GetExecutingAssembly().GetName().Version?.ToString();
                Console.WriteLine($"Puma Compiler version {versionNumber}");
                return;
            }

            // If the source file name is empty, print an error message and return.  Otherwise, read the source file.
            if (SourceFileName != "")
            {
                source = File.ReadAllText(SourceFileName);
            }
            else
            {
                Console.WriteLine("Error: No source file specified.");
                return;
            }

            // Create instances of the lexer, parser, and codegen classes.
            var lexer = new Lexer();
            var parser = new Parser();
            var codegen = new Codegen();

            // Tokenize and parse the source string above.
            // Generate C code from the syntax tree generated by the parser.

            var tokens = lexer.Tokenize(source);
            var ast = parser.Parse(tokens);
            var cCode = codegen.Generate(ast);

            if (Verbose)
            {
                // Print the C code to the console if the verbose flag is set.
                Console.WriteLine("C language IR:");
                Console.WriteLine(cCode);
            }

            if (EmitC)
            {
                // Write the generated C code to a file with the same name as the source file, but with the .c extension.
                File.WriteAllText(cSourceFileName, cCode);
                return;
            }

            if (OutputFileName != "")
            {
                ClangArguments = $"{cSourceFileName} -o {OutputFileName} {ClangArguments}"; // add the arguments after the source file name.
            }
            else
            {
                ClangArguments = $"{cSourceFileName} {ClangArguments}"; // add the arguments after the source file name.
            }

            // Compile the generated C code using clang.
            BuildGeneratedCode();
        }

        private static void ParseCommandArguments(string[] args)
        {
            foreach (var arg in args)
            {
                switch (arg)
                {
                    case "-v":
                    case "--verbose":
                        // Print verbose output.
                        Verbose = true;
                        // output file name won't follow this flag.
                        Output = false;
                        break;

                    case "-h":
                    case "--help":
                        // Print the help message. Return without compiling the source file.
                        Help = true;
                        // output file name won't follow this flag.
                        Output = false;
                        break;

                    case "-V":
                    case "--version":
                        // Print the version of the Puma compiler. Return without compiling the source file.
                        Version = true;
                        // output file name won't follow this flag.
                        Output = false;
                        break;

                    case "-emit-c":
                        // Emit the generated C code to a file. Return without compiling the source file.
                        EmitC = true;
                        // output file name won't follow this flag.
                        Output = false;
                        break;

                    case "-o":
                    case "--output":
                        // The next argument after this flag is the output file name.
                        Output = true;
                        break;

                    default:
                        if (Output)
                        {
                            // If the output flag is set, the argument that follows is the output file name.
                            OutputFileName = arg;
                            Output = false;
                            break;
                        }
                        // If the argument ends with ".puma", it is the source file name.
                        else if (arg.EndsWith(".puma"))
                        {
                            SourceFileName = arg;
                        }
                        else
                        {
                            // Otherwise, add the argument to the clang arguments string.
                            ClangArguments += args + " ";
                        }
                        break;
                }
            }
        }

        private static void BuildGeneratedCode()
        {
            var process = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = "clang",
                    Arguments = ClangArguments,
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                }

            };
            // run the clang compiler by calling the WaitForExit method.
            process.Start();
            process.WaitForExit();
        }

        private static void PrintHelp()
        {
            Console.WriteLine("Usage: puma [options] file.puma");
            Console.WriteLine("Options:");
            Console.WriteLine("  -v, --verbose  Print verbose output.");
            Console.WriteLine("  -h, --help     Print this help message and exit.");
            Console.WriteLine("  -V, --version  Print the version of the Puma compiler and exit.");
            Console.WriteLine("  -emit-c        Emit the generated C code to a file and exit.");
            Console.WriteLine("  -o, --output   Specify the output file name.");
            Console.WriteLine("  <clang flag>   other clang flags.");
        }
    }
}