<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>Puma.Program</StartupObject>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <AssemblyVersion>0.1</AssemblyVersion>
    <FileVersion>0.0.2.0</FileVersion>
    <PublishAot>True</PublishAot>
    <Description>LLVM compiler for the puma programming language.</Description>
    <Copyright>Copyright © 2024 - 2026 by Darryl Anthony Burchfield</Copyright>
    <PackageReleaseNotes>Initial release</PackageReleaseNotes>
    <Title>Puma Programming Language</Title>
    <Company>Puma Programming Language Project</Company>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>compiler; translator</PackageTags>
    <Version>0.1.0</Version>
    <PumaInstallDirectory>$(USERPROFILE)\Puma</PumaInstallDirectory>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Puma.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Puma.Tests\**" />
    <Compile Remove="test\**" />
    <None Remove="Puma.Tests\**" />
    <None Remove="test\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\CODEOWNERS" />
    <None Include=".github\copilot-instructions.md" />
    <None Include=".github\DOCOWNERS" />
    <None Include=".github\FUNDING.yml" />
    <None Include=".github\upgrades\scenarios\new-dotnet-version_7f6cdd\plan.md" />
    <None Include="Puma.Tests\Puma.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="tmp\" />
  </ItemGroup>

  <Target Name="InstallPumaCompiler" AfterTargets="Build">
    <MakeDir Directories="$(PumaInstallDirectory)" />
    <ItemGroup>
      <PumaCompilerArtifacts Include="$(TargetPath)" />
      <PumaCompilerArtifacts Include="$(TargetDir)$(AssemblyName).exe" Condition="Exists('$(TargetDir)$(AssemblyName).exe')" />
      <PumaCompilerArtifacts Include="$(TargetDir)$(AssemblyName).deps.json" Condition="Exists('$(TargetDir)$(AssemblyName).deps.json')" />
      <PumaCompilerArtifacts Include="$(TargetDir)$(AssemblyName).runtimeconfig.json" Condition="Exists('$(TargetDir)$(AssemblyName).runtimeconfig.json')" />
    </ItemGroup>
    <Copy SourceFiles="@(PumaCompilerArtifacts)" DestinationFolder="$(PumaInstallDirectory)\" />
  </Target>

</Project>
